site_name: Bullethell X Modding Guide

nav:
  - Home: index.md
  - Getting Started:
    - Creating a First Boss: getting_started.md
    - Making some Tweaks: making_tweaks.md
  - Scripting Basics:
    - Entity Component System: scripting_basics.md
    - The Engine Interface: engine_interface.md
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - content.tabs.link
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - attr_list
  - md_in_html
  - pymdownx.superfences

extra:
  # generator: false
  social:
    - icon: fontawesome/brands/x-twitter
      # link: https://twitter.com/aeroboxgames
    - icon: fontawesome/brands/instagram
      # link: https://www.instagram.com/aeroboxgames?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==
    - icon: fontawesome/brands/discord
      # link: https://www.instagram.com/aeroboxgames?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==

copyright: Copyright &copy; 2020 - 2025 Aerobox Games
